# ── Calibration integration for src/engine/ml_leg_scorer.py ──────────────────
# Strategy: Stat-Specific
# Generated by: scripts/calibrate_model.py
# Calibrator:   /home/gweeod/mlb-agent/scripts/../models/calibration/stat_specific_calibrator.pkl

import pickle

# Load once at module level (alongside the main model load)
with open("/home/gweeod/mlb-agent/scripts/../models/calibration/stat_specific_calibrator.pkl", "rb") as _f:
    CALIBRATOR = pickle.load(_f)


def apply_calibration(composite_score: float, stat: str = None) -> float:
    """Apply stat-specific isotonic calibration; falls back to identity for unknown stats."""
    calibrators = CALIBRATOR["calibrator"]
    if stat in calibrators:
        return float(calibrators[stat].predict([composite_score / 100])[0]) * 100
    return composite_score  # unknown stat — pass through unchanged


# ── Usage in score_legs_ml() ─────────────────────────────────────────────────
# After setting leg["composite_score"] = round(float(p) * 100, 2), add:
#
#   leg["composite_score"] = round(
#       apply_calibration(leg["composite_score"], leg.get("stat")), 2
#   )
