"""
formatter.py — Convert pipeline data into Discord embeds and message chunks.

All display logic lives here. runner.py produces raw data; this file turns
it into discord.Embed objects and plain-text strings ready to post.

Discord limits to be aware of:
  - Single message: 2000 characters
  - Embed description: 4096 characters
  - Embed field value: 1024 characters
  - Total embed size: 6000 characters
  - Embeds per message: 10

The helpers here split content to stay within these limits.
"""
from __future__ import annotations

from datetime import date

import discord


# ── Colour palette ────────────────────────────────────────────────────────────

COLOUR_GREEN  = 0x2ECC71   # solid / won
COLOUR_YELLOW = 0xF1C40F   # marginal / pending
COLOUR_RED    = 0xE74C3C   # skip / lost
COLOUR_BLUE   = 0x3498DB   # neutral info


def _chunk_text(text: str, limit: int = 1900) -> list[str]:
    """
    Split text into chunks no longer than limit characters, breaking on newlines.

    Prefers splitting at newline boundaries so Markdown formatting is preserved.
    Falls back to a hard split if a single line exceeds limit.

    Args:
        text: The full text to split.
        limit: Maximum characters per chunk (default 1900, below Discord's 2000).

    Returns:
        List of string chunks, each within the character limit.
    """
    if len(text) <= limit:
        return [text]

    chunks = []
    current = ""
    for line in text.splitlines(keepends=True):
        if len(current) + len(line) > limit:
            if current:
                chunks.append(current)
            # Hard-split lines that are themselves too long
            while len(line) > limit:
                chunks.append(line[:limit])
                line = line[limit:]
            current = line
        else:
            current += line
    if current:
        chunks.append(current)
    return chunks


# ── /run formatter ────────────────────────────────────────────────────────────

def format_run_header(n_parlays: int) -> discord.Embed:
    """
    Build the header embed posted before individual parlay embeds.

    Shows today's date and how many parlays were found.

    Args:
        n_parlays: Number of parlays generated by the pipeline.

    Returns:
        A discord.Embed to post first in the /run response.
    """
    embed = discord.Embed(
        title=f"MLB Parlay Agent — {date.today()}",
        description=f"Pipeline complete. **{n_parlays} parlay(s)** found.",
        colour=COLOUR_BLUE,
    )
    return embed


def format_parlay_embed(parlay: dict, index: int) -> discord.Embed:
    """
    Build a Discord embed for a single parlay.

    Shows odds, coverage, EV, and each leg with its key stats. Colour-codes
    by average coverage: green ≥ 75%, yellow ≥ 65%, red below that.

    Args:
        parlay: A parlay dict as returned by run_pipeline(), with 'legs' list.
        index: 1-based parlay number for the embed title.

    Returns:
        A discord.Embed representing the parlay.
    """
    avg_cov = parlay.get("avg_coverage", 0)
    colour = COLOUR_GREEN if avg_cov >= 75 else (COLOUR_YELLOW if avg_cov >= 65 else COLOUR_RED)

    ev_str = f" | avg EV {parlay['avg_ev']:+.1%}" if parlay.get("avg_ev") is not None else ""
    embed = discord.Embed(
        title=f"Parlay {index}  •  {parlay['parlay_odds']}",
        description=f"**{parlay['num_legs']} legs** | avg coverage {avg_cov}%{ev_str}",
        colour=colour,
    )

    legs_lines = []
    for leg in parlay.get("legs", []):
        p_str  = f" P={leg['p_over']:.0%}" if leg.get("p_over") else ""
        ev_str = f" EV={leg['ev_per_unit']:+.0%}" if leg.get("ev_per_unit") is not None else ""
        team_str = f" ({leg['team']})" if leg.get("team") else ""
        dl = "u" if leg.get("direction") == "under" else "o"
        legs_lines.append(
            f"• **{leg['player_name']}**{team_str} {leg['stat']} {dl}{leg['best_line']}"
            f" ({leg['best_odds']})  hist={leg['coverage_pct']}%{p_str}{ev_str}"
        )

    embed.add_field(name="Legs", value="\n".join(legs_lines) or "—", inline=False)
    return embed


def format_analysis_chunks(analysis: str) -> list[str]:
    """
    Split the LLM analysis text into Discord-safe message chunks.

    The Claude analysis can exceed 2000 characters, so this splits it on
    newline boundaries while staying under the 1900-character safe limit.

    Args:
        analysis: The full plain-English analysis string from Claude.

    Returns:
        List of message strings, each safe to post individually.
    """
    if not analysis:
        return []
    return _chunk_text(analysis.strip(), limit=1900)


# ── /status formatter ─────────────────────────────────────────────────────────

def format_status_embed(pending: list[dict]) -> discord.Embed:
    """
    Build a Discord embed showing all pending (unresolved) recommendations.

    Lists each pending parlay with its date, odds, and leg count. If nothing
    is pending, returns an embed saying so.

    Args:
        pending: List of parlay dicts as returned by runner.pipeline_status().

    Returns:
        A discord.Embed summarising pending recommendations.
    """
    if not pending:
        return discord.Embed(
            title="Status — Pending Recommendations",
            description="No pending recommendations. Run `/resolve` if games have finished.",
            colour=COLOUR_BLUE,
        )

    embed = discord.Embed(
        title="Status — Pending Recommendations",
        description=f"{len(pending)} parlay(s) awaiting resolution.",
        colour=COLOUR_YELLOW,
    )

    for rec in pending:
        leg_lines = []
        for leg in rec.get("legs", []):
            result_icon = {"won": "✅", "lost": "❌", "pending": "⏳", "void": "🚫"}.get(leg.get("result", "pending"), "⏳")
            team_str = f" ({leg['team']})" if leg.get("team") else ""
            leg_lines.append(
                f"{result_icon} {leg['player_name']}{team_str} o{leg['line']}"
            )
        embed.add_field(
            name=f"{rec['date']}  •  {rec['parlay_odds']}  •  {rec['num_legs']} legs",
            value="\n".join(leg_lines) or "—",
            inline=False,
        )

    return embed


# ── /resolve formatter ────────────────────────────────────────────────────────

def format_resolve_chunks(output: str) -> list[str]:
    """
    Split the outcome resolver's text output into Discord-safe message chunks.

    Args:
        output: Raw text output captured from resolve_recommendations().

    Returns:
        List of message strings, each within Discord's character limit.
    """
    if not output:
        return ["Resolver complete — nothing to update."]
    return _chunk_text(output, limit=1900)


# ── /calibration formatter ────────────────────────────────────────────────────

def format_calibration_embed(data: dict) -> discord.Embed:
    """
    Build a Discord embed for the model calibration report.

    Shows leg hit rate, parlay hit rate, Brier scores for Bayesian vs
    historical coverage, calibration buckets, and EV accuracy. If no
    resolved data exists yet, returns an instructional embed.

    Args:
        data: Calibration metrics dict as returned by runner.pipeline_calibration().

    Returns:
        A discord.Embed with the full calibration report.
    """
    if data.get("n_legs", 0) == 0:
        return discord.Embed(
            title="Calibration Report",
            description="No resolved legs yet. Run `/resolve` after games complete.",
            colour=COLOUR_BLUE,
        )

    embed = discord.Embed(
        title="Model Calibration Report",
        colour=COLOUR_GREEN,
    )

    # Hit rates
    hit_rate = data["leg_hit_rate"]
    hit_colour = "✅" if hit_rate >= 0.65 else ("⚠️" if hit_rate >= 0.5 else "❌")
    embed.add_field(
        name="Leg Hit Rate",
        value=f"{hit_colour} {data['leg_wins']}/{data['n_legs']} = **{hit_rate:.1%}**",
        inline=True,
    )

    if data.get("parlay_hit_rate") is not None:
        p_rate = data["parlay_hit_rate"]
        embed.add_field(
            name="Parlay Hit Rate",
            value=f"{data['parlay_wins']}/{data['n_parlays']} = **{p_rate:.1%}**",
            inline=True,
        )

    # Brier scores
    brier_lines = []
    if data.get("brier_bayes") is not None:
        brier_lines.append(f"Bayesian P(over): **{data['brier_bayes']:.4f}** (n={data['n_bayes_legs']})")
    if data.get("brier_cov") is not None:
        brier_lines.append(f"Historical cov %: **{data['brier_cov']:.4f}** (n={data['n_cov_legs']})")
    if data.get("brier_bayes") and data.get("brier_cov"):
        diff = data["brier_cov"] - data["brier_bayes"]
        better = "Bayes" if diff > 0 else "Coverage"
        brier_lines.append(f"→ **{better}** is better by {abs(diff / data['brier_cov']):.1%}")
    if brier_lines:
        embed.add_field(name="Brier Scores (lower = better)", value="\n".join(brier_lines), inline=False)

    # Calibration buckets
    buckets = data.get("calibration_buckets", [])
    if buckets:
        bucket_lines = []
        for b in buckets:
            gap = b["actual_rate"] - b["predicted_avg"]
            flag = " ← overconfident" if gap < -0.08 else (" ← underconfident" if gap > 0.08 else "")
            bucket_lines.append(
                f"`{b['range']}` pred {b['predicted_avg']:.0%} → actual **{b['actual_rate']:.0%}**"
                f" (n={b['count']}){flag}"
            )
        embed.add_field(name="Bayesian Calibration Buckets", value="\n".join(bucket_lines), inline=False)

    # EV accuracy
    ev_lines = []
    if data["pos_ev_total"] > 0:
        rate = data["pos_ev_wins"] / data["pos_ev_total"]
        ev_lines.append(f"Positive EV legs: {data['pos_ev_wins']}/{data['pos_ev_total']} won = **{rate:.1%}**")
    if data["neg_ev_total"] > 0:
        rate = data["neg_ev_wins"] / data["neg_ev_total"]
        ev_lines.append(f"Negative EV legs: {data['neg_ev_wins']}/{data['neg_ev_total']} won = **{rate:.1%}**")
    if ev_lines:
        embed.add_field(name="EV Accuracy", value="\n".join(ev_lines), inline=False)

    return embed
